export const produc = [
  {
    _id: "prod1",
    image: "alternator.png",
    title: "Alternator",
    href: "/search-by-part-name/Alternator",
    price: 500,
    description:"Alternators for all vehicles are manufactured using Quality Standards and 100% end-of-line computerised.",
  },
  {
    _id: "prod2",
    image: "battery.png",
    title: "Battery",
    href: "/search-by-part-name/Battery",
    price: 200,
    description:"The Automobile Batteries are manufactured using the best quality raw materials that has a high power, performance and reliability.",
  },
  {
    _id: "prod3",
    image: "brake.png",
    title: "Brake Booster",
    href: "/search-by-part-name/Brake Booster",
    price: 300,
    description:"Braking system from high end manufacturers using high quality metallic, carbon-based, brass bonded resins, steel and graphite in UAE.",
  },
  {
    _id: "prod4",
    image: "catalytic-converter.png",
    title: "Catalytic Converter",
    href: "/search-by-part-name/Convertible Top",
    price: 500,
    description:"High quality Catalytic Converter that helps reducing noxious air pollutions. Expect only the most standard quality from us in UAE",
  },
  {
    _id: "prod5",
    image: "engine.png",
    title: "Engine",
    href: "/search-by-part-name/Engine",
    price: 200,
    description:"Get comprehensive list of vehicle engines quotated at the best price in UAE. High quality and low mielage engines are available with us in UAE",
  },
  {
    _id: "prod6",
    image: "axle.png",
    title: "Front Axle",
    href: "Axle Beam (Front, 2WD)",
    price: 400,
    description:"Axles for any kind of road transport highly reliable and higher end quality at the great deals in UAE",
  },
  {
    _id: "prod7",
    image: "tank.png",
    title: "Fuel Tank",
    href: "/search-by-part-name/Fuel Tank",
    price: 800,
    description:"Huge variety of storage from 500 litres to 1,20,000 litres of fuel tankers for fabricating and building a fuel/ diesel tankers in carbon steel stalls in UAE.",
  },
  {
    _id: "prod8",
    image: "muffler.png",
    title: "Muffler",
    href: "/search-by-part-name/Exhaust Manifold",
    price: 800,
    description:"Raise the power and sound of your vehicle with our good quality Muffler at best prices Muffler in UAE.",
  },
  {
    _id: "prod9",
    image: "radiator.png",
    title: "Radiator",
    href: "/search-by-part-name/Radiator",
    price: 800,
    description:"Well performing radiator at best price in UAE for top tanks, bottom tanks and the core radiator which is the largest part of it.",
  },
  {
    _id: "prod11",
    image: "tailpipe.png",
    title: "Tailgate",
    href: "/search-by-part-name/Tailgate",
    price: 800,
    description:"Get Increased peak power of exhaust parts by reducing the back pressure which can be void of factory warranties in UAE",
  },
  {
    _id: "prod12",
    image: "transmission.png",
    title: "GearBox",
    href: "/search-by-part-name/Transmission Control Module",
    price: 800,
    description:"Increase your shaft speed with reduced torque with our high quality Transmission from the best higher end manufacturer in UAE",
  },
];

export default produc;
