export const carLogos = [
  { id: 1, logo: "ford.png", name: "Ford", alt: "Auto spare parts in uae" },
  {
    id: 2,
    logo: "chrysler.png",
    name: "Chrysler",
    alt: "Auto spare parts in uae",
  },
  {
    id: 3,
    logo: "citroen.png",
    name: "Citroen",
    alt: "Auto spare parts in uae",
  },
  {
    id: 4,
    logo: "hillman.png",
    name: "Hillman",
    alt: "Auto spare parts in uae",
  },
  {
    id: 5,
    logo: "chevrolet.png",
    name: "Chevrolet",
    alt: "Auto spare parts in uae",
  },
  {
    id: 6,
    logo: "cadillac.png",
    name: "Cadillac",
    alt: "Auto spare parts in uae",
  },
  { id: 7, logo: "bmw.png", name: "BMW", alt: "Auto spare parts in uae" },
  { id: 8, logo: "austin.png", name: "Austin", alt: "Auto spare parts in uae" },
  {
    id: 9,
    logo: "fairthorpe.jpg",
    name: "Fairthorpe",
    alt: "Auto spare parts in uae",
  },
  {
    id: 10,
    logo: "fillmore.png",
    name: "Fillmore",
    alt: "Auto spare parts in uae",
  },
  {
    id: 11,
    logo: "pontiac.png",
    name: "Pontiac",
    alt: "Auto spare parts in uae",
  },
  {
    id: 12,
    logo: "studebaker.png",
    name: "Studebaker",
    alt: "Auto spare parts in uae",
  },
  { id: 13, logo: "buick.png", name: "Buick", alt: "Auto spare parts in uae" },
  {
    id: 14,
    logo: "rambler.png",
    name: "Rambler",
    alt: "Auto spare parts in uae",
  },
  {
    id: 15,
    logo: "plymouth.png",
    name: "Plymouth",
    alt: "Auto spare parts in uae",
  },
  {
    id: 16,
    logo: "volkswagon.png",
    name: "Volkswagon",
    alt: "Auto spare parts in uae",
  },
  {
    id: 17,
    logo: "jensen.png",
    name: "Jensen",
    alt: "Auto spare parts in uae",
  },
  {
    id: 18,
    logo: "oldsmobile.png",
    name: "Oldsmobile",
    alt: "Auto spare parts in uae",
  },
  {
    id: 19,
    logo: "mercury.png",
    name: "Mercury",
    alt: "Auto spare parts in uae",
  },
  { id: 20, logo: "dodge.png", name: "Dodge", alt: "Auto spare parts in uae" },
  {
    id: 21,
    logo: "shelby.png",
    name: "Shelby",
    alt: "Auto spare parts in uae",
  },
  {
    id: 22,
    logo: "porsche.png",
    name: "Porsche",
    alt: "Auto spare parts in uae",
  },
  {
    id: 23,
    logo: "toyota.png",
    name: "Toyota",
    alt: "Auto spare parts in uae",
  },
  {
    id: 24,
    logo: "mercedesbenz.png",
    name: "Mercedes-Benz",
    alt: "Auto spare parts in uae",
  },
  { id: 25, logo: "mg.png", name: "MG", alt: "Auto spare parts in uae" },
  {
    id: 26,
    logo: "nissan.png",
    name: "Nissan",
    alt: "Auto spare parts in uae",
  },
  { id: 27, logo: "honda.png", name: "Honda", alt: "Auto spare parts in uae" },
  { id: 28, logo: "mazda.png", name: "Mazda", alt: "Auto spare parts in uae" },
  {
    id: 29,
    logo: "renault.png",
    name: "Renault",
    alt: "Auto spare parts in uae",
  },
  { id: 30, logo: "audi.png", name: "Audi", alt: "Auto spare parts in uae" },
  {
    id: 31,
    logo: "lincoln.png",
    name: "Lincoln",
    alt: "Auto spare parts in uae",
  },
  { id: 32, logo: "lotus.png", name: "Lotus", alt: "Auto spare parts in uae" },
  {
    id: 33,
    logo: "maserati.png",
    name: "Maserati",
    alt: "Auto spare parts in uae",
  },
  {
    id: 34,
    logo: "mitsubishi.png",
    name: "Mitsubishi",
    alt: "Auto spare parts in uae",
  },
  { id: 35, logo: "saab.png", name: "Saab", alt: "Auto spare parts in uae" },
  {
    id: 36,
    logo: "subaru.png",
    name: "Subaru",
    alt: "Auto spare parts in uae",
  },
  {
    id: 37,
    logo: "suzuki.png",
    name: "Suzuki",
    alt: "Auto spare parts in uae",
  },
  {
    id: 38,
    logo: "lamborghini.png",
    name: "Lamborghini",
    alt: "Auto spare parts in uae",
  },
  {
    id: 39,
    logo: "merkur.png",
    name: "Merkur",
    alt: "Auto spare parts in uae",
  },
  {
    id: 40,
    logo: "land_rover.png",
    name: "Land Rover",
    alt: "Auto spare parts in uae",
  },
  { id: 41, logo: "acura.png", name: "Acura", alt: "Auto spare parts in uae" },
  { id: 42, logo: "lexus.png", name: "Lexus", alt: "Auto spare parts in uae" },
  { id: 43, logo: "eagle.png", name: "Eagle", alt: "Auto spare parts in uae" },
  {
    id: 44,
    logo: "alfa_romeo.png",
    name: "Alfa Romeo",
    alt: "Auto spare parts in uae",
  },
  {
    id: 45,
    logo: "daihat.png",
    name: "Daihatsu",
    alt: "Auto spare parts in uae",
  },
  { id: 46, logo: "geo.png", name: "Geo", alt: "Auto spare parts in uae" },
  { id: 47, logo: "gmc.png", name: "GMC", alt: "Auto spare parts in uae" },
  {
    id: 48,
    logo: "hyundai.png",
    name: "Hyundai",
    alt: "Auto spare parts in uae",
  },
  {
    id: 49,
    logo: "infiniti.png",
    name: "Infiniti",
    alt: "Auto spare parts in uae",
  },
  { id: 50, logo: "isuzu.png", name: "Isuzu", alt: "Auto spare parts in uae" },
  {
    id: 51,
    logo: "jaguar.png",
    name: "Jaguar",
    alt: "Auto spare parts in uae",
  },
  { id: 52, logo: "jeep.png", name: "Jeep", alt: "Auto spare parts in uae" },
  {
    id: 53,
    logo: "saturn.png",
    name: "Saturn",
    alt: "Auto spare parts in uae",
  },
  { id: 54, logo: "volvo.png", name: "Volvo", alt: "Auto spare parts in uae" },
  {
    id: 55,
    logo: "hummer.png",
    name: "HUMMER",
    alt: "Auto spare parts in uae",
  },
  { id: 56, logo: "kia.png", name: "Kia", alt: "Auto spare parts in uae" },
  {
    id: 57,
    logo: "holden.png",
    name: "Holden",
    alt: "Auto spare parts in uae",
  },
  {
    id: 58,
    logo: "corbin.png",
    name: "Corbin",
    alt: "Auto spare parts in uae",
  },
  {
    id: 59,
    logo: "daewoo.png",
    name: "Daewoo",
    alt: "Auto spare parts in uae",
  },
  { id: 60, logo: "mini.png", name: "MINI", alt: "Auto spare parts in uae" },
  {
    id: 61,
    logo: "maybach.png",
    name: "Maybach",
    alt: "Auto spare parts in uae",
  },
  { id: 62, logo: "scion.png", name: "Scion", alt: "Auto spare parts in uae" },
  {
    id: 63,
    logo: "spyker.png",
    name: "Spyker",
    alt: "Auto spare parts in uae",
  },
  {
    id: 64,
    logo: "aston_martin.png",
    name: "Aston Martin",
    alt: "Auto spare parts in uae",
  },
  {
    id: 65,
    logo: "bentley.png",
    name: "Bentley",
    alt: "Auto spare parts in uae",
  },
  { id: 66, logo: "panoz.png", name: "Panoz", alt: "Auto spare parts in uae" },
  {
    id: 67,
    logo: "rolls-royce.png",
    name: "Rolls-Royce",
    alt: "Auto spare parts in uae",
  },
  {
    id: 68,
    logo: "spyker cars.png",
    name: "Spyker Cars",
    alt: "Auto spare parts in uae",
  },
  {
    id: 69,
    logo: "ferrari.png",
    name: "Ferrari",
    alt: "Auto spare parts in uae",
  },
  {
    id: 70,
    logo: "hummer.png",
    name: "Hummer",
    alt: "Auto spare parts in uae",
  },
  {
    id: 71,
    logo: "morgan.png",
    name: "Morgan",
    alt: "Auto spare parts in uae",
  },
  {
    id: 72,
    logo: "peugeot.png",
    name: "Peugeot",
    alt: "Auto spare parts in uae",
  },
  { id: 73, logo: "foose.png", name: "Foose", alt: "Auto spare parts in uae" },
  {
    id: 74,
    logo: "aptera.png",
    name: "Aptera",
    alt: "Auto spare parts in uae",
  },
  { id: 75, logo: "smart.png", name: "Smart", alt: "Auto spare parts in uae" },
  {
    id: 76,
    logo: "bugatti.png",
    name: "Bugatti",
    alt: "Auto spare parts in uae",
  },
  { id: 77, logo: "tesla.png", name: "Tesla", alt: "Auto spare parts in uae" },
  { id: 78, logo: "ram.png", name: "Ram", alt: "Auto spare parts in uae" },
  { id: 79, logo: "fiat.png", name: "FIAT", alt: "Auto spare parts in uae" },
  { id: 80, logo: "fiat.png", name: "Fiat", alt: "Auto spare parts in uae" },
  {
    id: 81,
    logo: "mclaren.png",
    name: "McLaren",
    alt: "Auto spare parts in uae",
  },
  { id: 82, logo: "byd.png", name: "BYD", alt: "Auto spare parts in uae" },
  {
    id: 83,
    logo: "mclaren.png",
    name: "McLaren Automotive",
    alt: "Auto spare parts in uae",
  },
  {
    id: 84,
    logo: "venturi.png",
    name: "Mobility Ventures LLC",
    alt: "Auto spare parts in uae",
  },
  {
    id: 85,
    logo: "pagani.png",
    name: "Pagani",
    alt: "Auto spare parts in uae",
  },
  {
    id: 86,
    logo: "roush_performance.png",
    name: "Roush Performance",
    alt: "Auto spare parts in uae",
  },
  { id: 87, logo: "smart.png", name: "smart", alt: "Auto spare parts in uae" },
  { id: 88, logo: "srt.png", name: "SRT", alt: "Auto spare parts in uae" },
  {
    id: 89,
    logo: "genesis.png",
    name: "Genesis",
    alt: "Auto spare parts in uae",
  },
  { id: 90, logo: "karma.png", name: "Karma", alt: "Auto spare parts in uae" },
  {
    id: 91,
    logo: "koenigsegg.png",
    name: "Koenigsegg",
    alt: "Auto spare parts in uae",
  },
  {
    id: 92,
    logo: "ruf.png",
    name: "RUF Automobile",
    alt: "Auto spare parts in uae",
  },
  { id: 93, logo: "sti.png", name: "STI", alt: "Auto spare parts in uae" },
  {
    id: 94,
    logo: "polestar.png",
    name: "Polestar",
    alt: "Auto spare parts in uae",
  },
  {
    id: 95,
    logo: "kandi.png",
    name: "Kandi",
    alt: "Auto spare parts in uae in uae",
  },
];

export default carLogos;